### PR TITLE
Merge paper

### PR DESCRIPTION
**Pull request by fsih**
Pull in the last year of updates from paper.js head

### CODE REVIEW

**Comment by paulkaplan** [comment]
errrmmmm how should i review this?

**Comment by fsih** [comment]
Mostly check that I haven't botched our scratch-specific changes. I tested
the integration with gui and it looked fine to me, but it would be cool if
you'd like to check it too.

**Comment by fsih** [comment]
How did we review scratch blocks merges?

**Comment by paulkaplan** [comment]
Ok I tested that it is still working on scratch-paint. I can't get my env linked correctly to test through to GUI, but I would just make sure that the text importing/exporting is still working correctly, that is one of the only places we really specialized it. LGTM otherwise

**Comment by fsih** [comment]
Text import looks good to me

**Pull request merged**
