### PR TITLE
Fix Build and move changes from dist file to source files

### PR DESCRIPTION
**Pull request by fsih**
We had changes that were just in the dist/paper-full.js file, and I've moved those to source files. Fixed tests and got npm deploy working.

### CODE REVIEW

**Review by rschamp — CHANGES_REQUESTED** [review]
This is hard to review since it combines a few things. Would you please you do the merge separately and make a PR with just the changes to the build process?

**Comment by fsih** [comment]
I broke out the code moved from dist to src in https://github.com/LLK/paper.js/pull/3

**Review by rschamp — COMMENTED** [review]
Can we remove the built files from the repo if we're building in Travis? We might need to change what happens in Travis and build before testing.  Keeping the build checked in can make PRs really annoying to read (and commits annoying to make since you have to remember to rebuild).

**Comment by fsih** [comment]
Thanks! I got the tests to build before they run and took out the dist files.

**Review by rschamp — APPROVED** [review]

**Pull request merged**
